// frontend/src/components/form/CountrySelect.tsx
import { Select } from "chakra-react-select";
import { countries } from 'country-data';

type CountrySelectProps = {
    availableCountries: string[];
    onChange?: (country?: string) => void;
}

const CountrySelect = ({ availableCountries, onChange }: CountrySelectProps) => {
    const options = availableCountries
        .map(countryCode => countries[countryCode])
        .map(country => ({
            label: `${country.emoji} ${country.name}`,
            value: country.alpha2,
        }))

    return (
        <Select onChange={newValue => onChange && onChange(newValue?.value)} options={options} />
    );
}

export default CountrySelect;

// frontend/src/components/CountrySelect.svelte
<script lang="ts">
	import { i18n } from '@/services/i18n';
	import { Select, SelectItem } from 'carbon-components-svelte';
	import { countries } from 'country-data';

	export let labelText: string = $i18n.t('components.countryselect.label');
	export let availableCountries: string[];
	export let selected: string | undefined = undefined;

	const options = availableCountries
		.map((countryCode) => countries[countryCode])
		.map((country) => ({
			label: `${country.emoji} ${country.name}`,
			value: country.alpha2
		}));
</script>

<Select {labelText} bind:selected {...$$restProps}>
	<SelectItem text="" />
	{#each options as { label, value }}
		<SelectItem text={label} {value} />
	{/each}
</Select>
